apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
patches:
  - path: fail-first-patch.yaml
    target:
      group: cascade.cascade.net
      version: v1alpha1
      kind: CascadeManualOperator
      name: cascademanualoperator.*
      labelSelector: "app=cascade"

