{{- range .Values.cluster_roles }}
---
{{- if eq .cluster_role_binding true }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "cascadeManualOperator.labels" $ | nindent 4 }}
  name: {{ include "cascadeManualOperator.name" $ }}-{{ .name }}-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cascadeManualOperator.name" $ }}-{{ .name }}
subjects:
- kind: {{ .kind }}
  name: {{ include "cascadeManualOperator.serviceAccountName" $ }}
  namespace: {{ $.Release.Namespace }}
{{- end }}
{{- end }}