{{- range .Values.roles }}
---
{{- if eq .enabled true }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    {{- include "cascadeManualOperator.labels" $ | nindent 4 }}
  name: {{ include "cascadeManualOperator.name" $ }}-{{ .name }}
rules: 
{{ toYaml .rules }}
{{- end }}
{{- end }}