apiVersion: cascade.cascade.net/v1alpha1
kind: CascadeManualOperator
metadata:
  name: cascademanualoperator-sample
spec:
  template:
    spec:
      containers:
        - name: test-job
          image: busybox
          command:
            - sleep
            - "2000"
      restartPolicy: OnFailure
  # TODO(user): Add fields here
