apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cascade_manual_scenario.yaml

patches:
  - path: minio-address-patch.yaml
    target:
      group: cascade.cascade.net
      version: v1alpha1
      kind: CascadeManualOperator
      name: cascademanualoperator.*
      labelSelector: "app=cascade"
images:
- name: ghcr.io/randsw/cascadescenariocontroller
  newTag: 0.2.6